# Generated by Django 2.2 on 2019-04-03 05:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField()),
                ('is_seller', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('photo', models.ImageField(default='media/images/profile-default-lrg.png', upload_to='media/images/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
