# Generated by Django 2.2 on 2019-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(default='images/profile-default-lrg.png', upload_to='images/'),
        ),
    ]
