# Generated by Django 2.2 on 2019-04-09 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0002_auto_20190408_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('panaji', 'Panaji'), ('New Delhi', 'New Delhi'), ('Faridabad', 'Faridabad'), ('Chandigarh', 'Chandigarh')], max_length=20)),
                ('state', models.CharField(choices=[('goa', 'Goa'), ('delhi', 'Delhi'), ('haryana', 'Haryana'), ('punjab', 'Punjab')], max_length=20)),
                ('pin', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('sq_feet', models.IntegerField()),
                ('lot_size', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('property_listing_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('main_image', models.ImageField(default='images_property/default_property.jpg', upload_to='images_property/')),
                ('photo1', models.ImageField(blank=True, upload_to='images_property/')),
                ('photo2', models.ImageField(blank=True, upload_to='images_property/')),
                ('photo3', models.ImageField(blank=True, upload_to='images_property/')),
                ('photo4', models.ImageField(blank=True, upload_to='images_property/')),
                ('photo5', models.ImageField(blank=True, upload_to='images_property/')),
                ('photo6', models.ImageField(blank=True, upload_to='images_property/')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
